spring:
  application:
    name: feign-client
  security:
    user:
      name: client
      password: pwd

server:
  port: 8080
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      # If you have more eureka replicas add them here seperated by ,
      defaultZone: http://admin:password@localhost:8761/eureka

serverApi:
  username: server
  password: pass
  serverDiscoveryName: server

management:
  endpoints:
    web:
      exposure:
        include: metrics, info, health
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  application:
    name: '@project.name@'
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'